from collections.abc import Iterable, Mapping, Sequence
from typing import Any, Literal, overload

import numpy as np
import numpy.typing as npt

class DeviceCommutationMatrix:
    @staticmethod
    def empty(shape: tuple[int, int], device: int = ..., backend: str | None = ...) -> DeviceCommutationMatrix: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def device(self) -> int: ...
    @property
    def backend(self) -> Literal["cuda", "hip", "metal"]: ...
    @property
    def dtype(self) -> Literal["uint8"]: ...
    @property
    def num_entries(self) -> int: ...
    def to_host(self) -> npt.NDArray[np.bool_]: ...
    @overload
    def count_commuting(self, axis: None = ...) -> int: ...
    @overload
    def count_commuting(self, axis: Literal[0, 1]) -> npt.NDArray[np.uint64]: ...
    @overload
    def conflict_degrees(self, axis: None = ...) -> int: ...
    @overload
    def conflict_degrees(self, axis: Literal[0, 1]) -> npt.NDArray[np.uint64]: ...
    def __dlpack__(self, stream: int | None = ..., max_version: tuple[int, int] | None = ..., copy: bool | None = ...) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...

class DevicePauliSum:
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_terms(self) -> int: ...
    @property
    def device(self) -> int: ...
    @property
    def backend(self) -> Literal["cuda", "hip", "metal"]: ...
    def to_host(self) -> PauliSum: ...
    def simplify(self, atol: float = ..., rtol: float = ...) -> DevicePauliSum: ...
    def expectation_statevector(self, psi: Any) -> complex: ...
    def commutes_with(self, other: DevicePauliSum, max_commutation_matrix_entries: int = ...) -> bool | npt.NDArray[np.bool_]: ...
    def commutes_with_device(self, other: DevicePauliSum, max_commutation_matrix_entries: int = ..., output: DeviceCommutationMatrix | None = ...) -> DeviceCommutationMatrix: ...
    def commutes_with_into(self, other: DevicePauliSum, output: npt.NDArray[np.bool_], max_commutation_matrix_entries: int = ...) -> None: ...
    def matmul(self, rhs: DevicePauliSum, simplify: bool = ..., max_intermediate_terms: int = ...) -> DevicePauliSum: ...

class PauliSum:
    def __init__(self, num_qubits: int, num_terms: int) -> None: ...
    @staticmethod
    def empty(num_qubits: int) -> PauliSum: ...
    @staticmethod
    def from_labels(labels: Iterable[str], coeffs: Any | None = ...) -> PauliSum: ...
    @staticmethod
    def from_sparse_list(triples: Iterable[tuple[str, Sequence[int], complex]], num_qubits: int) -> PauliSum: ...
    @staticmethod
    def from_qiskit(operator: Any) -> PauliSum: ...
    @staticmethod
    def from_openfermion(operator: Any, num_qubits: int | None = ...) -> PauliSum: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_terms(self) -> int: ...
    def to_labels(self) -> tuple[list[str], npt.NDArray[np.complex128]]: ...
    def to_sparse_list(self) -> list[tuple[str, list[int], complex]]: ...
    def to_qiskit(self) -> Any: ...
    def to_openfermion(self) -> Any: ...
    def simplify(self, atol: float = ..., rtol: float = ...) -> PauliSum: ...
    def matmul(self, rhs: PauliSum, simplify: bool = ..., max_intermediate_terms: int = ...) -> PauliSum: ...
    def commutes_with(self, other: PauliSum, max_commutation_matrix_entries: int = ...) -> bool | npt.NDArray[np.bool_]: ...
    def group_commuting(self, mode: Literal["qwc", "full"] = ..., strategy: Literal["largest_first"] = ..., max_terms_for_graph: int = ...) -> list[PauliSum]: ...
    def expectation_statevector(self, psi: Any) -> complex: ...
    def expectation_z_counts(self, counts: Mapping[Any, int]) -> complex: ...
    def to_device(self, device: int = ..., backend: Literal["auto", "cuda", "hip", "metal"] | None = ...) -> DevicePauliSum: ...
    def __add__(self, rhs: PauliSum) -> PauliSum: ...
    def __mul__(self, scalar: complex) -> PauliSum: ...
    def __rmul__(self, scalar: complex) -> PauliSum: ...
    def __matmul__(self, rhs: PauliSum) -> PauliSum: ...

def cuda_available() -> bool: ...
def cuda_devices() -> list[dict[str, Any]]: ...
def hip_available() -> bool: ...
def hip_devices() -> list[dict[str, Any]]: ...
def metal_available() -> bool: ...
def metal_devices() -> list[dict[str, Any]]: ...
def _build_info() -> dict[str, Any]: ...
def _cuda_status() -> dict[str, Any]: ...
def _hip_status() -> dict[str, Any]: ...
def _metal_status() -> dict[str, Any]: ...
